{% set name = "napari-hierarchical" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-hierarchical-{{ version }}.tar.gz
  sha256: edd4dd75e6abe038a0a4c2b35da374779c313674750bb4d21932d6fe5ed3bc02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - napari >=0.4.17
    - pluggy
    - python >=3.8,<3.11
    - qtpy

test:
  imports:
    - napari_hierarchical
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BodenmillerGroup/napari-hierarchical
  summary: Hierarchical file format support for napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jwindhager
